import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <head>
            <meta charSet="UTF-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
            <title>PetAdopt - Find a Shelter</title>
            <link rel="stylesheet" href="css/style.css"/>
        </head>
        <body>
          {children}
        </body>
      </html>
  );
}
